/**
 * Core telemetry and event types for SentinelOS
 * Supports massive scale ingestion with unified schema
 */

import { z } from 'zod';

/**
 * Severity levels for security events
 */
export enum SeverityLevel {
  CRITICAL = 'critical',
  HIGH = 'high',
  MEDIUM = 'medium',
  LOW = 'low',
  INFO = 'info',
}

/**
 * Event types across the security stack
 */
export enum EventType {
  // EDR Events
  PROCESS_CREATION = 'process.creation',
  PROCESS_TERMINATION = 'process.termination',
  FILE_CREATION = 'file.creation',
  FILE_MODIFICATION = 'file.modification',
  FILE_DELETION = 'file.deletion',
  REGISTRY_MODIFICATION = 'registry.modification',
  NETWORK_CONNECTION = 'network.connection',
  DNS_QUERY = 'dns.query',

  // Identity Events
  LOGIN_SUCCESS = 'login.success',
  LOGIN_FAILURE = 'login.failure',
  PASSWORD_CHANGE = 'password.change',
  PERMISSION_CHANGE = 'permission.change',
  GROUP_MEMBERSHIP_CHANGE = 'group.membership.change',

  // Cloud Events
  RESOURCE_CREATION = 'resource.creation',
  RESOURCE_DELETION = 'resource.deletion',
  PERMISSION_GRANTED = 'permission.granted',
  PERMISSION_REVOKED = 'permission.revoked',
  CONFIGURATION_CHANGE = 'configuration.change',

  // Network Events
  FIREWALL_BLOCK = 'firewall.block',
  IDS_ALERT = 'ids.alert',
  PROXY_LOG = 'proxy.log',

  // Detection Engine
  ANOMALY_DETECTED = 'anomaly.detected',
  BEHAVIORAL_ALERT = 'behavioral.alert',
  THREAT_DETECTED = 'threat.detected',

  // Remediation
  REMEDIATION_EXECUTED = 'remediation.executed',
  REMEDIATION_FAILED = 'remediation.failed',
}

/**
 * Core telemetry event schema
 * Designed for massive scale and high cardinality
 */
export interface TelemetryEvent {
  // Unique identification
  event_id: string;
  timestamp: number; // milliseconds since epoch
  source_system: string; // CrowdStrike, Splunk, Okta, etc.
  event_type: EventType;

  // Entity information
  entity_type: 'endpoint' | 'identity' | 'cloud_resource' | 'network' | 'application';
  entity_id: string;
  entity_name: string;

  // Severity and classification
  severity: SeverityLevel;
  classification: string[];

  // Actual event data
  data: Record<string, any>;

  // Enrichment data
  enrichment: {
    threat_intel?: {
      indicator_type: string;
      indicator_value: string;
      threat_level: 'critical' | 'high' | 'medium' | 'low';
      source: string;
    };
    asset_info?: {
      asset_type: string;
      criticality: 'critical' | 'high' | 'medium' | 'low';
      owner: string;
      tags: string[];
    };
  };

  // Raw source data
  raw_data: string; // JSON stringified original event
}

/**
 * Alert generated by detection engine
 */
export interface SecurityAlert {
  alert_id: string;
  timestamp: number;
  title: string;
  description: string;
  severity: SeverityLevel;

  // Investigation context
  investigation_id?: string;
  investigation_status?: 'pending' | 'investigating' | 'resolved' | 'false_positive';

  // Related events
  related_event_ids: string[];

  // Graph entities involved
  entities: {
    type: 'endpoint' | 'identity' | 'resource' | 'indicator';
    id: string;
    name: string;
  }[];

  // Detection metadata
  detection_rule_id: string;
  detection_type: 'sigma' | 'yara' | 'ai_anomaly' | 'behavioral' | 'threshold' | 'ml_model';

  // Confidence score
  confidence: number; // 0-1
  false_positive_score?: number; // 0-1

  // Custom fields
  metadata: Record<string, any>;
}

/**
 * Investigation context for autonomous analysis
 */
export interface Investigation {
  investigation_id: string;
  alert_id: string;
  created_at: number;
  updated_at: number;

  // Investigation lifecycle
  status: 'pending' | 'investigating' | 'escalated' | 'resolved' | 'archived';
  confidence: number; // 0-1

  // Analysis findings
  findings: {
    title: string;
    description: string;
    severity: SeverityLevel;
    evidence: string[];
  }[];

  // Recommended actions
  recommendations: {
    action: string;
    priority: 'critical' | 'high' | 'medium' | 'low';
    confidence: number;
    estimated_impact: string;
  }[];

  // Attack information
  attack_chain?: {
    stages: {
      stage: string;
      techniques: string[];
      indicators: string[];
    }[];
    estimated_impact: string;
  };

  // Investigation timeline
  timeline: {
    timestamp: number;
    event: string;
    event_type: string;
    severity: SeverityLevel;
  }[];

  // Analyst notes
  notes: string;

  // Automated analysis results
  ai_analysis?: {
    summary: string;
    key_insights: string[];
    risk_assessment: string;
    recommendations: string[];
  };
}

/**
 * Remediation action to be executed
 */
export interface RemediationAction {
  action_id: string;
  investigation_id: string;

  // Action details
  action_type:
    | 'isolate_endpoint'
    | 'disable_account'
    | 'revoke_session'
    | 'block_indicator'
    | 'rotate_credential'
    | 'patch_system'
    | 'custom_command';

  description: string;
  target: {
    type: 'endpoint' | 'identity' | 'resource' | 'indicator' | 'application';
    id: string;
    name: string;
  };

  // Execution parameters
  parameters: Record<string, any>;

  // Confidence and approval
  confidence: number; // 0-1
  approval_required: boolean;
  approval_status?: 'pending' | 'approved' | 'rejected';
  approver?: string;

  // Execution status
  status: 'pending' | 'executing' | 'completed' | 'failed' | 'rolled_back';
  execution_timestamp?: number;
  result?: {
    success: boolean;
    message: string;
    details: Record<string, any>;
  };

  // Rollback capability
  rollback_available: boolean;
  rollback_action?: RemediationAction;
}

/**
 * Threat graph entity
 */
export interface ThreatGraphEntity {
  entity_id: string;
  entity_type:
    | 'endpoint'
    | 'identity'
    | 'resource'
    | 'indicator'
    | 'threat_actor'
    | 'malware'
    | 'vulnerability'
    | 'privilege'
    | 'process'
    | 'file';

  name: string;
  display_name: string;

  // Properties
  properties: Record<string, any>;

  // Risk scoring
  risk_score: number; // 0-100
  criticality: 'critical' | 'high' | 'medium' | 'low';

  // Timeline
  first_seen: number;
  last_seen: number;

  // Relationships
  incoming_relationships: Array<{
    relationship_type: string;
    source_entity_id: string;
    properties?: Record<string, any>;
  }>;
  outgoing_relationships: Array<{
    relationship_type: string;
    target_entity_id: string;
    properties?: Record<string, any>;
  }>;
}

/**
 * Detection rule definition
 */
export interface DetectionRule {
  rule_id: string;
  name: string;
  description: string;

  // Rule source
  rule_type: 'sigma' | 'yara' | 'ai_model' | 'threshold' | 'behavioral' | 'custom';
  rule_content: string; // YAML, regex, or custom format

  // Rule metadata
  author: string;
  created: number;
  modified: number;

  // Detection parameters
  severity: SeverityLevel;
  confidence: number;
  false_positive_rate: number;

  // Coverage
  mitre_techniques: string[];
  threat_actors: string[];

  // Status
  enabled: boolean;
  version: string;
}

/**
 * Validation schemas using Zod
 */
export const TelemetryEventSchema = z.object({
  event_id: z.string().uuid(),
  timestamp: z.number(),
  source_system: z.string(),
  event_type: z.nativeEnum(EventType),
  entity_type: z.enum(['endpoint', 'identity', 'cloud_resource', 'network', 'application']),
  entity_id: z.string(),
  entity_name: z.string(),
  severity: z.nativeEnum(SeverityLevel),
  classification: z.array(z.string()),
  data: z.record(z.any()),
  enrichment: z.object({
    threat_intel: z.optional(z.object({
      indicator_type: z.string(),
      indicator_value: z.string(),
      threat_level: z.enum(['critical', 'high', 'medium', 'low']),
      source: z.string(),
    })),
    asset_info: z.optional(z.object({
      asset_type: z.string(),
      criticality: z.enum(['critical', 'high', 'medium', 'low']),
      owner: z.string(),
      tags: z.array(z.string()),
    })),
  }),
  raw_data: z.string(),
});

export type ValidatedTelemetryEvent = z.infer<typeof TelemetryEventSchema>;
